version: "3.9"

services:
  db:
    image: mysql:8.0
    container_name: event_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: thefrienddb
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

  app:
    build: .
    container_name: event_app
    depends_on:
      - db
    environment:
      DATABASE_URL: mysql+pymysql://root:password@db:3306/thefrienddb
    ports:
      - "8000:8000"
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

volumes:
  db_data:
